Kondrashov_rpmbuild_ASCCIGraphic: Kondrashov_rpmbuild_ASCCIGraphic.cpp
	g++ Kondrashov_rpmbuild_ASCCIGraphic.cpp -o Kondrashov_rpmbuild_ASCCIGraphic -lncursesw -ltinfo -lm
clear:
	rm ./Kondrashov_rpmbuild_ASCCIGraphic
